######################################################################
# Automatically generated by qmake (2.01a) Thu Jul 4 14:06:05 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
SOURCES += main.cpp widget.cpp
